macro browser dialog with treeWidget (#3539)
* macro browser treeWidget

- handle network error without message box
- qmap for deterministic order

* solution with metatype macro for Qt5

s. template selector

* fix interference with templateselector.h

```
/home/runner/work/texstudio/texstudio/texstudio_autogen/UVLADIE3JM/../../src/templateselector.h:110:1: error: redefinition of ‘struct QMetaTypeId<QTreeWidgetItem*>’
  110 | Q_DECLARE_METATYPE(QTreeWidgetItem *)
      | ^~~~~~~~~~~~~~~~~~
/home/runner/work/texstudio/texstudio/texstudio_autogen/UVLADIE3JM/../../src/macrobrowserui.h:51:1: note: previous definition of ‘struct QMetaTypeId<QTreeWidgetItem*>’
   51 | Q_DECLARE_METATYPE(QTreeWidgetItem *)
```

* remove itemCache

* use iterator flag

* remove unused variable

* remove unused variable in header file